name = "ReSolverInterface"
uuid = "9a172a43-bfaf-4cc4-8edb-b32fc4c49da3"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
