name = "ReSolverInterface"
uuid = "9a172a43-bfaf-4cc4-8edb-b32fc4c49da3"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
